// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2813.LeftoverRover.robot;

import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DigitalOutput;
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	
    public static SpeedController pIDDrivefrontLeft;
    public static SpeedController pIDDrivefrontRight;
    public static SpeedController pIDDrivebackLeft;
    public static SpeedController pIDDrivebackRight;
	public static RobotDrive drive;
    public static Solenoid solenoid;
    public static Relay leftRelay;
    public static Relay rightRelay;
    public static Compressor compressor;
	public static DigitalOutput elevatorGet;

    public static void init() {
    	
    	pIDDrivefrontLeft = new Talon(5);
        LiveWindow.addActuator("PIDDrive", "frontLeft", (Talon) pIDDrivefrontLeft);
        
        pIDDrivefrontRight = new Talon(2);
        LiveWindow.addActuator("PIDDrive", "frontRight", (Talon) pIDDrivefrontRight);
        
        pIDDrivebackLeft = new Talon(4);
        LiveWindow.addActuator("PIDDrive", "backLeft", (Talon) pIDDrivebackLeft);
        
        pIDDrivebackRight = new Talon(3);
        LiveWindow.addActuator("PIDDrive", "backRight", (Talon) pIDDrivebackRight);
        
        drive = new RobotDrive(pIDDrivefrontLeft, pIDDrivebackLeft,
        		pIDDrivefrontRight, pIDDrivebackRight);
        
        drive.setSafetyEnabled(true);
        drive.setExpiration(0.1);
        drive.setSensitivity(0.5);
        drive.setMaxOutput(1.0);
        
        solenoid = new Solenoid(0);
        LiveWindow.addActuator("ShirtLauncher", "Solenoid", solenoid);
        
        leftRelay = new Relay(0);
        LiveWindow.addActuator("ShirtLauncher", "LeftRelay", leftRelay);
        
        rightRelay = new Relay(1);
        LiveWindow.addActuator("ShirtLauncher", "RightRelay", rightRelay);
        
    }
    
}
